const PlaceTypes = [
  { key: 'accounting', value: 'Accounting' },
  { key: 'airport', value: 'Airport' },
  { key: 'amusement_park', value: 'Amusement park' },
  { key: 'aquarium', value: 'Aquarium' },
  { key: 'art_gallery', value: 'Art gallery' },
  { key: 'atm', value: 'Atm' },
  { key: 'bakery', value: 'Bakery' },
  { key: 'bank', value: 'Bank' },
  { key: 'bar', value: 'Bar' },
  { key: 'beauty_salon', value: 'Beauty salon' },
  { key: 'bicycle_store', value: 'Bicycle store' },
  { key: 'book_store', value: 'Book store' },
  { key: 'bowling_alley', value: 'Bowling alley' },
  { key: 'bus_station', value: 'Bus station' },
  { key: 'cafe', value: 'Cafe' },
  { key: 'campground', value: 'Campground' },
  { key: 'car_dealer', value: 'Car dealer' },
  { key: 'car_rental', value: 'Car rental' },
  { key: 'car_repair', value: 'Car repair' },
  { key: 'car_wash', value: 'Car wash' },
  { key: 'casino', value: 'Casino' },
  { key: 'cemetery', value: 'Cemetery' },
  { key: 'church', value: 'Church' },
  { key: 'city_hall', value: 'City hall' },
  { key: 'clothing_store', value: 'Clothing store' },
  { key: 'convenience_store', value: 'Convenience store' },
  { key: 'courthouse', value: 'Courthouse' },
  { key: 'dentist', value: 'Dentist' },
  { key: 'department_store', value: 'Department store' },
  { key: 'doctor', value: 'Doctor' },
  { key: 'drugstore', value: 'Drugstore' },
  { key: 'electrician', value: 'Electrician' },
  { key: 'electronics_store', value: 'Electronics store' },
  { key: 'embassy', value: 'Embassy' },
  { key: 'fire_station', value: 'Fire station' },
  { key: 'florist', value: 'Florist' },
  { key: 'funeral_home', value: 'Funeral home' },
  { key: 'furniture_store', value: 'Furniture store' },
  { key: 'gas_station', value: 'Gas station' },
  { key: 'gym', value: 'Gym' },
  { key: 'hair_care', value: 'Hair care' },
  { key: 'hardware_store', value: 'Hardware store' },
  { key: 'hindu_temple', value: 'Hindu temple' },
  { key: 'home_goods_store', value: 'Home goods store' },
  { key: 'hospital', value: 'Hospital' },
  { key: 'insurance_agency', value: 'Insurance agency' },
  { key: 'jewelry_store', value: 'Jewelry store' },
  { key: 'laundry', value: 'Laundry' },
  { key: 'lawyer', value: 'Lawyer' },
  { key: 'library', value: 'Library' },
  { key: 'light_rail_station', value: 'Light rail station' },
  { key: 'liquor_store', value: 'Liquor store' },
  { key: 'local_government_office', value: 'Local government office' },
  { key: 'locksmith', value: 'Locksmith' },
  { key: 'lodging', value: 'Lodging' },
  { key: 'meal_delivery', value: 'Meal delivery' },
  { key: 'meal_takeaway', value: 'Meal takeaway' },
  { key: 'mosque', value: 'Mosque' },
  { key: 'movie_rental', value: 'Movie rental' },
  { key: 'movie_theater', value: 'Movie theater' },
  { key: 'moving_company', value: 'Moving company' },
  { key: 'museum', value: 'Museum' },
  { key: 'night_club', value: 'Night club' },
  { key: 'painter', value: 'Painter' },
  { key: 'park', value: 'Park' },
  { key: 'parking', value: 'Parking' },
  { key: 'pet_store', value: 'Pet store' },
  { key: 'pharmacy', value: 'Pharmacy' },
  { key: 'physiotherapist', value: 'Physiotherapist' },
  { key: 'plumber', value: 'Plumber' },
  { key: 'police', value: 'Police' },
  { key: 'post_office', value: 'Post office' },
  { key: 'primary_school', value: 'Primary school' },
  { key: 'real_estate_agency', value: 'Real estate agency' },
  { key: 'restaurant', value: 'Restaurant' },
  { key: 'roofing_contractor', value: 'Roofing contractor' },
  { key: 'rv_park', value: 'Rv park' },
  { key: 'school', value: 'School' },
  { key: 'secondary_school', value: 'Secondary school' },
  { key: 'shoe_store', value: 'Shoe_store' },
  { key: 'shopping_mall', value: 'Shopping mall' },
  { key: 'spa', value: 'Spa' },
  { key: 'stadium', value: 'Stadium' },
  { key: 'storage', value: 'Storage' },
  { key: 'store', value: 'Store' },
  { key: 'subway_station', value: 'Subway station' },
  { key: 'supermarket', value: 'Supermarket' },
  { key: 'synagogue', value: 'Synagogue' },
  { key: 'taxi_stand', value: 'Taxi stand' },
  { key: 'tourist_attraction', value: 'Tourist attraction' },
  { key: 'train_station', value: 'Train station' },
  { key: 'transit_station', value: 'Transit station' },
  { key: 'travel_agency', value: 'Travel agency' },
  { key: 'university', value: 'University' },
  { key: 'veterinary_care', value: 'Veterinary care' },
  { key: 'zoo', value: 'Zoo' },
];

export default PlaceTypes;
